apiVersion: v1
kind: Namespace
metadata:
  name: VictorOK-python-app

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-app
          image: obimadu/im-base-fastapi
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"
