apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-deployment
  labels:
    app: ${APP_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APP_NAME}
  template:
    metadata:
      labels:
        app: ${APP_NAME}
    spec:
      containers:
        - name: ${APP_NAME}
          image: obimadu/im-base-fastapi
          resources:
            limits:
              memory: "1Gi"
              cpu: "500m"

---
apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
